name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O master, dependiendo de cómo se llame su rama principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Construir la versión Web (PWA)
        # El comando por defecto de flutter build web ya genera una PWA
        run: flutter build web --release --base-href /Microproyecto-Sistemas-de-Informacion/

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web